---

- name: running tcode from windows
  hosts: inmbz2081.in.dst.ibm.com
  tasks:
    - name: running tocode
      #win_command: C:\Users\ansible\Downloads\dr\download\demo1.bat
      win_command: python C:\Users\ansible\Downloads\dr\download\Tcode_SM21.py
      register: result

    - name: debug output
      debug:
        var: result  
